import { NextRequest, NextResponse } from "next/server";
import { ApiError, errorResponse } from "@/server/core/api";
import { requireAuthenticatedUser } from "@/server/auth/guards";
import { getOrderById } from "@/server/domain/orders";

export const dynamic = "force-dynamic";

type RouteContext = {
  params: Promise<{ orderId: string }>;
};

export async function POST(request: NextRequest, context: RouteContext) {
  try {
    const user = await requireAuthenticatedUser(request);
    const { orderId } = await context.params;
    const order = await getOrderById(orderId);
    if (!order) {
      throw new ApiError("NOT_FOUND", 404, "Order not found.");
    }

    if (user.role !== "admin" && order.customer_email !== user.email.toLowerCase()) {
      throw new ApiError("FORBIDDEN", 403, "You do not have access to this order.");
    }

    if (order.fulfillment_status !== "delivered") {
      throw new ApiError("CONFLICT", 409, "Order fulfillment is not complete yet.");
    }

    const summary = [
      `Order ${order.order_number}`,
      `Customer: ${order.customer_name}`,
      `Email: ${order.customer_email}`,
      order.selected_tier_name ? `Tier: ${order.selected_tier_name}` : null,
      order.selected_variant_slug ? `Variant: ${order.selected_variant_slug}` : null,
      order.selected_fulfillment_type ? `Fulfillment: ${order.selected_fulfillment_type}` : null,
      `Items: ${order.items.map((item) => `${item.product_name} x${item.quantity}`).join(", ")}`,
      `Total: ${order.total_cents / 100} ${order.currency}`,
      "Delivery package: manual fulfillment summary generated by the current release.",
    ]
      .filter((line): line is string => Boolean(line))
      .join("\n");

    return new NextResponse(summary, {
      status: 200,
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Content-Disposition": `attachment; filename="${order.order_number}.txt"`,
      },
    });
  } catch (error) {
    return errorResponse(error instanceof Error ? error : new ApiError("INTERNAL_ERROR", 500, "Unable to download order."));
  }
}
