export const languageOptions = [
  { code: "en", label: "ENGLISH", locale: "en-US" },
  { code: "fr", label: "FRANCAIS", locale: "fr-FR" },
  { code: "es", label: "ESPANOL", locale: "es-ES" },
] as const;

export const currencyOptions = ["USD", "EUR", "GBP"] as const;

export type LanguageCode = (typeof languageOptions)[number]["code"];
export type CurrencyCode = (typeof currencyOptions)[number];

export const preferenceKeys = {
  language: "growrix-language",
  currency: "growrix-currency",
  authSession: "growrix-auth-session",
};

const fallbackLanguage: LanguageCode = "en";
const fallbackCurrency: CurrencyCode = "USD";

const currencyRatesFromUsd: Record<CurrencyCode, number> = {
  USD: 1,
  EUR: 0.92,
  GBP: 0.79,
};

const messages: Record<LanguageCode, Record<string, string>> = {
  en: {
    "common.home": "Home",
    "common.shop": "Shop",
    "common.account": "Account",
    "common.login": "Login",
    "common.register": "Register",
    "common.checkout": "Checkout",
    "common.success": "Success",
    "common.blog": "Blog",
    "common.search": "Search",
    "common.category": "Category",
    "common.contact": "Contact Us",
    "common.about": "About Us",
    "common.dailyDeals": "Daily Deals",
    "common.readMore": "Read More",
    "common.loadMore": "Load More",
    "common.submit": "Submit",
    "common.remove": "Remove",
    "common.goToShop": "Go To Shop",
    "common.continueShopping": "Continue Shopping",
    "common.viewAccount": "View Account",
    "common.clearCart": "Clear Cart",
    "common.proceedCheckout": "Proceed To Checkout",
    "common.placeOrder": "Place Order",
    "common.by": "By",
    "common.searchAction": "Search",

    "nav.hotline": "Hotline",
    "nav.loginRegister": "Login / Register",
    "nav.account": "My Account",
    "nav.logout": "Logout",
    "nav.myCart": "My Cart",
    "nav.search": "Search",
    "nav.itemSingular": "item",
    "nav.itemPlural": "items",
    "nav.home": "HOME",
    "nav.shop": "SHOP",
    "nav.deals": "DEALS",
    "nav.under100": "UNDER $100",
    "nav.newArrivals": "NEW ARRIVALS",
    "nav.blog": "BLOG",
    "nav.about": "ABOUT US",
    "nav.contact": "CONTACT US",

    "footer.followUs": "FOLLOW US",
    "footer.newsletterTitle": "SIGN UP FOR NEWSLETTER",
    "footer.newsletterThanks": "Thanks, you are subscribed.",
    "footer.contactUs": "CONTACT US",
    "footer.storeLocation": "STORE LOCATION",
    "footer.customerService": "CUSTOMER SERVICE",
    "footer.information": "INFORMATION",
    "footer.replicationNote": "Built as a production-ready Next.js storefront.",

    "newsletter.title": "Newsletter Subscribe",
    "newsletter.description": "Subscribe to the mailing list to receive updates on new arrivals, special offers and other discount information.",
    "newsletter.subscribed": "Thanks, your subscription is active.",
    "newsletter.doNotShow": "Don't show this popup again",
    "newsletter.placeholder": "Your email address",
    "newsletter.cta": "SUBSCRIBE",

    "home.welcome": "Welcome to {siteName}",
    "home.heroTop": "THE BEST",
    "home.heroBottom": "AUTOMOTIVE SHOP",
    "home.heroDescription": "A complete automotive storefront with strong contrast, fast discovery, and conversion-focused shopping flows.",
    "home.exploreNow": "EXPLORE NOW",
    "home.slide2Eyebrow": "Track-ready confidence",
    "home.slide2Top": "PRECISION",
    "home.slide2Bottom": "BRAKING UPGRADE",
    "home.slide2Description": "Upgrade control with performance brake kits and reinforced components built for confident daily and weekend driving.",
    "home.slide2Cta": "SHOP BRAKE KITS",
    "home.slide3Eyebrow": "Save bigger this week",
    "home.slide3Top": "LIMITED",
    "home.slide3Bottom": "DAILY DEALS",
    "home.slide3Description": "Discover rotating markdowns across tires, tools, and replacement parts before inventory windows close.",
    "home.slide3Cta": "VIEW DEALS",
    "home.prevSlide": "Previous slide",
    "home.nextSlide": "Next slide",
    "home.selectVehicle": "Select Your Vehicle",
    "home.vehicleSubtitle": "Over 120,000 automotive and truck parts",
    "home.topSelection": "Top selection this week",
    "home.bestSellers": "Best Sellers",
    "home.recentPosts": "Our recent posts",
    "home.latestBlogs": "Latest Blogs",
    "home.featureFreeShipping": "FREE SHIPPING",
    "home.featureFreeShippingText": "On orders over {amount}",
    "home.featureMoneyGuarantee": "MONEY GUARANTEE",
    "home.featureMoneyGuaranteeText": "30 days money back guarantee",
    "home.featureSafeShopping": "SAFE SHOPPING",
    "home.featureSafeShoppingText": "Safe shopping guarantee",
    "home.featureOnlineSupport": "ONLINE SUPPORT",
    "home.featureOnlineSupportText": "We support 24/7 every day",
    "home.newArrivals": "NEW ARRIVALS",
    "home.bestSellersColumn": "BEST SELLERS",
    "home.saleOff": "SALE OFF",

    "shop.subtitle": "Discover premium automotive products with complete browsing and purchase flows.",
    "shop.noProducts": "No products are available in this category yet.",

    "search.results": "SEARCH RESULTS",
    "search.query": "Query",
    "search.make": "Make",
    "search.model": "Model",
    "search.year": "Year",
    "search.noResults": "No products matched your search. Try another keyword or adjust your filters.",
    "search.placeholder": "Search products",
    "search.selectMake": "Select Make",
    "search.selectModel": "Select Model",
    "search.selectYear": "Select Year",

    "cart.title": "MY CART",
    "cart.empty": "Your cart is empty. Browse products in the shop to add items.",
    "cart.subtotal": "Subtotal",

    "checkout.title": "CHECKOUT",
    "checkout.orderSummary": "Order Summary",
    "checkout.items": "Items",
    "checkout.empty": "Your cart is empty. Add products before checking out.",
    "checkout.fullName": "Full Name",
    "checkout.email": "Email",
    "checkout.address": "Address",
    "checkout.city": "City",
    "checkout.postalCode": "Postal Code",

    "checkout.successTitle": "ORDER CONFIRMED",
    "checkout.successMessage": "Your order has been placed successfully. You can continue browsing the catalog or review your account for the latest order status.",

    "product.sku": "SKU",
    "product.inStock": "In Stock",
    "product.category": "Category",
    "product.addToCart": "Add To Cart",
    "product.added": "Added",
    "product.descriptionTitle": "Product Description",
    "product.featuresTitle": "Key Features",
    "product.descriptionBody1": "{title} is engineered for drivers who expect dependable daily performance and confident response under load.",
    "product.descriptionBody2": "Built for the {category} segment, this item balances durability, fit accuracy, and clean installation for modern automotive projects.",
    "product.featureCompatibility": "Fitment aligned with {category} setups",
    "product.featureInventory": "{stock} units currently available for quick dispatch",
    "product.featureUseCase": "Recommended for: {tags}",
    "product.featureWarranty": "Quality-tested materials for long-term reliability",

    "account.title": "MY ACCOUNT",
    "account.profileOverview": "Profile Overview",
    "account.profileDescription": "Keep account preferences updated so language, currency, and checkout defaults remain consistent across sessions.",
    "account.currentPreferences": "Current Preferences",
    "account.language": "Language",
    "account.currency": "Currency",
    "account.guestTitle": "Guest Session",
    "account.guestDescription": "Sign in or create an account to save your profile and checkout preferences.",
    "account.signInNow": "Sign In Now",
    "account.registerNow": "Register Now",

    "auth.loginTitle": "LOGIN",
    "auth.registerTitle": "REGISTER",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signIn": "Sign In",
    "auth.createAccount": "Create Account",
    "auth.loginSuccess": "Signed in successfully for this demo session.",
    "auth.registerSuccess": "Registration completed for this demo session.",
    "auth.noAccount": "Don't have an account?",
    "auth.haveAccount": "Already have an account?",
    "auth.fullName": "Full Name",

    "contact.title": "CONTACT US",
    "contact.intro": "We love to hear from you! Please let us know if you have any questions or concerns and we will get back to you within 2 business days. Thanks!",
    "contact.name": "Name",
    "contact.phone": "Phone Number",
    "contact.message": "Leave A Comment",
    "contact.success": "Thank you, your message has been submitted.",
    "contact.submitting": "SUBMITTING...",
    "contact.submitFailed": "Unable to submit your message right now. Please try again.",

    "about.title": "ABOUT US",
    "about.intro1": "Growrix Auto is a clean automotive storefront concept focused on premium parts, trusted brands, and a fast shopping experience.",
    "about.intro2": "The layout combines a bold visual hierarchy with practical product discovery, so the storefront feels like a real e-commerce destination instead of a generic landing page.",
    "about.team": "Our Team Work",
    "about.locations": "Shop Location",

    "dailyDeals.title": "DAILY DEALS",
    "dailyDeals.days": "DAYS",
    "dailyDeals.hours": "HOURS",
    "dailyDeals.mins": "MINS",
    "dailyDeals.secs": "SECS",

    "blog.related": "Related Posts",
    "support.titleFallback": "Support",
    "support.customer-service.description": "Get direct assistance for product, order, and account questions.",
    "support.customer-service.content1": "Our customer service team supports order updates, product compatibility checks, and account assistance.",
    "support.customer-service.content2": "Use this page for general service requests and route-specific help guidance.",
    "support.shipping-returns.description": "Review shipping timelines and return eligibility policies.",
    "support.shipping-returns.content1": "Shipping estimates vary by region and item type. Tracking updates are published as soon as parcels are scanned by carriers.",
    "support.shipping-returns.content2": "Returns are accepted within the listed policy window when product condition and packaging requirements are met.",
    "support.track-order.description": "Look up fulfillment and delivery progress for your order.",
    "support.track-order.content1": "Track your order status using your order number and email confirmation details.",
    "support.track-order.content2": "If tracking has not updated within expected windows, submit a support request for escalation.",
    "support.help-center.description": "Browse frequently asked questions and setup guides.",
    "support.help-center.content1": "The help center includes installation guides, account troubleshooting, and checkout support articles.",
    "support.help-center.content2": "Use topic filters to find product family-specific answers quickly.",
    "support.store-location.description": "Find Growrix Auto locations and business hours.",
    "support.store-location.content1": "Store locations and service counters are listed with local operating hours.",
    "support.store-location.content2": "Appointment booking details are available for participating locations.",
    "support.customer-feedback.description": "Share product and service feedback with our team.",
    "support.customer-feedback.content1": "Customer feedback helps prioritize upcoming feature and catalog improvements.",
    "support.customer-feedback.content2": "Use this route to submit quality concerns, suggestions, or post-purchase comments.",
  },
  fr: {
    "common.home": "Accueil",
    "common.shop": "Boutique",
    "common.account": "Compte",
    "common.login": "Connexion",
    "common.register": "Inscription",
    "common.checkout": "Paiement",
    "common.success": "Succes",
    "common.blog": "Blog",
    "common.search": "Recherche",
    "common.category": "Categorie",
    "common.contact": "Contact",
    "common.about": "A propos",
    "common.dailyDeals": "Offres du jour",
    "common.readMore": "Lire plus",
    "common.loadMore": "Voir plus",
    "common.submit": "Envoyer",
    "common.remove": "Retirer",
    "common.goToShop": "Aller a la boutique",
    "common.continueShopping": "Continuer vos achats",
    "common.viewAccount": "Voir le compte",
    "common.clearCart": "Vider le panier",
    "common.proceedCheckout": "Passer au paiement",
    "common.placeOrder": "Passer la commande",
    "common.by": "Par",
    "common.searchAction": "Rechercher",

    "nav.hotline": "Assistance",
    "nav.loginRegister": "Connexion / Inscription",
    "nav.account": "Mon compte",
    "nav.logout": "Deconnexion",
    "nav.myCart": "Mon panier",
    "nav.search": "Recherche",
    "nav.itemSingular": "article",
    "nav.itemPlural": "articles",
    "nav.home": "ACCUEIL",
    "nav.shop": "BOUTIQUE",
    "nav.deals": "OFFRES",
    "nav.under100": "SOUS 100",
    "nav.newArrivals": "NOUVEAUTES",
    "nav.blog": "BLOG",
    "nav.about": "A PROPOS",
    "nav.contact": "CONTACT",

    "footer.followUs": "SUIVEZ-NOUS",
    "footer.newsletterTitle": "INSCRIPTION NEWSLETTER",
    "footer.newsletterThanks": "Merci, vous etes inscrit.",
    "footer.contactUs": "CONTACT",
    "footer.storeLocation": "MAGASINS",
    "footer.customerService": "SERVICE CLIENT",
    "footer.information": "INFORMATIONS",
    "footer.replicationNote": "Cree comme vitrine Next.js de niveau production.",

    "newsletter.title": "Abonnement newsletter",
    "newsletter.description": "Abonnez-vous pour recevoir les nouveautes, offres speciales et informations de reduction.",
    "newsletter.subscribed": "Merci, votre abonnement est actif.",
    "newsletter.doNotShow": "Ne plus afficher cette fenetre",
    "newsletter.placeholder": "Votre adresse email",
    "newsletter.cta": "S'ABONNER",

    "home.welcome": "Bienvenue chez {siteName}",
    "home.heroTop": "LE MEILLEUR",
    "home.heroBottom": "MAGASIN AUTO",
    "home.heroDescription": "Une vitrine auto complete avec contraste fort, recherche rapide et parcours d'achat optimise.",
    "home.exploreNow": "EXPLORER",
    "home.slide2Eyebrow": "Confiance prete pour la piste",
    "home.slide2Top": "PRECISION",
    "home.slide2Bottom": "FREINAGE AMELIORE",
    "home.slide2Description": "Ameliorez le controle avec des kits de frein performance et des composants renforces pour les trajets quotidiens et weekend.",
    "home.slide2Cta": "VOIR LES KITS FREIN",
    "home.slide3Eyebrow": "Economisez plus cette semaine",
    "home.slide3Top": "OFFRES",
    "home.slide3Bottom": "DU JOUR",
    "home.slide3Description": "Decouvrez des remises tournantes sur pneus, outils et pieces de remplacement avant la fin du stock promo.",
    "home.slide3Cta": "VOIR LES OFFRES",
    "home.prevSlide": "Diapositive precedente",
    "home.nextSlide": "Diapositive suivante",
    "home.selectVehicle": "Selectionnez votre vehicule",
    "home.vehicleSubtitle": "Plus de 120 000 pieces auto et camion",
    "home.topSelection": "Selection de la semaine",
    "home.bestSellers": "Meilleures ventes",
    "home.recentPosts": "Nos derniers posts",
    "home.latestBlogs": "Derniers blogs",
    "home.featureFreeShipping": "LIVRAISON GRATUITE",
    "home.featureFreeShippingText": "Sur les commandes de plus de {amount}",
    "home.featureMoneyGuarantee": "GARANTIE ARGENT",
    "home.featureMoneyGuaranteeText": "Garantie remboursement 30 jours",
    "home.featureSafeShopping": "ACHAT SECURISE",
    "home.featureSafeShoppingText": "Garantie d'achat securise",
    "home.featureOnlineSupport": "SUPPORT EN LIGNE",
    "home.featureOnlineSupportText": "Support 24/7 chaque jour",
    "home.newArrivals": "NOUVEAUTES",
    "home.bestSellersColumn": "MEILLEURES VENTES",
    "home.saleOff": "PROMOTIONS",

    "shop.subtitle": "Decouvrez des produits automobiles premium avec des parcours d'achat complets.",
    "shop.noProducts": "Aucun produit n'est encore disponible dans cette categorie.",

    "search.results": "RESULTATS DE RECHERCHE",
    "search.query": "Requete",
    "search.make": "Marque",
    "search.model": "Modele",
    "search.year": "Annee",
    "search.noResults": "Aucun produit ne correspond a votre recherche. Essayez un autre mot-cle ou ajustez vos filtres.",
    "search.placeholder": "Rechercher des produits",
    "search.selectMake": "Choisir la marque",
    "search.selectModel": "Choisir le modele",
    "search.selectYear": "Choisir l'annee",

    "cart.title": "MON PANIER",
    "cart.empty": "Votre panier est vide. Parcourez la boutique pour ajouter des articles.",
    "cart.subtotal": "Sous-total",

    "checkout.title": "PAIEMENT",
    "checkout.orderSummary": "Resume de commande",
    "checkout.items": "Articles",
    "checkout.empty": "Votre panier est vide. Ajoutez des produits avant le paiement.",
    "checkout.fullName": "Nom complet",
    "checkout.email": "Email",
    "checkout.address": "Adresse",
    "checkout.city": "Ville",
    "checkout.postalCode": "Code postal",

    "checkout.successTitle": "COMMANDE CONFIRMEE",
    "checkout.successMessage": "Votre commande a ete enregistree. Continuez vos achats ou consultez votre compte pour voir le statut.",

    "product.sku": "SKU",
    "product.inStock": "En stock",
    "product.category": "Categorie",
    "product.addToCart": "Ajouter au panier",
    "product.added": "Ajoute",
    "product.descriptionTitle": "Description produit",
    "product.featuresTitle": "Caracteristiques principales",
    "product.descriptionBody1": "{title} est concu pour les conducteurs qui attendent une performance quotidienne fiable et une reponse sure sous charge.",
    "product.descriptionBody2": "Concu pour le segment {category}, cet article combine durabilite, precision d'ajustement et installation propre pour les projets auto modernes.",
    "product.featureCompatibility": "Compatibilite adaptee aux configurations {category}",
    "product.featureInventory": "{stock} unites disponibles pour expedition rapide",
    "product.featureUseCase": "Recommande pour : {tags}",
    "product.featureWarranty": "Materiaux testes pour une fiabilite longue duree",

    "account.title": "MON COMPTE",
    "account.profileOverview": "Vue du profil",
    "account.profileDescription": "Gardez vos preferences a jour pour conserver langue, devise et paiement par defaut.",
    "account.currentPreferences": "Preferences actuelles",
    "account.language": "Langue",
    "account.currency": "Devise",
    "account.guestTitle": "Session invite",
    "account.guestDescription": "Connectez-vous ou creez un compte pour sauvegarder vos preferences.",
    "account.signInNow": "Se connecter",
    "account.registerNow": "Creer un compte",

    "auth.loginTitle": "CONNEXION",
    "auth.registerTitle": "INSCRIPTION",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.signIn": "Se connecter",
    "auth.createAccount": "Creer un compte",
    "auth.loginSuccess": "Connexion reussie pour cette session demo.",
    "auth.registerSuccess": "Inscription terminee pour cette session demo.",
    "auth.noAccount": "Vous n'avez pas de compte ?",
    "auth.haveAccount": "Vous avez deja un compte ?",
    "auth.fullName": "Nom complet",

    "contact.title": "CONTACT",
    "contact.intro": "Nous aimons recevoir vos messages. Partagez vos questions et nous repondrons sous 2 jours ouvrables.",
    "contact.name": "Nom",
    "contact.phone": "Numero de telephone",
    "contact.message": "Laisser un commentaire",
    "contact.success": "Merci, votre message a ete envoye.",
    "contact.submitting": "ENVOI...",
    "contact.submitFailed": "Impossible d'envoyer votre message pour le moment. Veuillez reessayer.",

    "about.title": "A PROPOS",
    "about.intro1": "Growrix Auto est un concept de boutique automobile propre, centre sur des pieces premium, des marques fiables et une experience d'achat rapide.",
    "about.intro2": "La mise en page combine une hierarchie visuelle forte et une recherche produit pratique pour donner une vraie experience e-commerce.",
    "about.team": "Notre equipe",
    "about.locations": "Magasins",

    "dailyDeals.title": "OFFRES DU JOUR",
    "dailyDeals.days": "JOURS",
    "dailyDeals.hours": "HEURES",
    "dailyDeals.mins": "MINS",
    "dailyDeals.secs": "SECS",

    "blog.related": "Articles lies",
    "support.titleFallback": "Support",
    "support.customer-service.description": "Obtenez une assistance directe pour les questions produit, commande et compte.",
    "support.customer-service.content1": "Notre equipe service client gere les mises a jour de commande, la compatibilite produit et l'assistance compte.",
    "support.customer-service.content2": "Utilisez cette page pour les demandes generales de service et l'aide liee aux parcours.",
    "support.shipping-returns.description": "Consultez les delais d'expedition et les conditions de retour.",
    "support.shipping-returns.content1": "Les estimations d'expedition varient selon la region et le type d'article. Le suivi est publie des que le transporteur scanne le colis.",
    "support.shipping-returns.content2": "Les retours sont acceptes dans la fenetre de politique indiquee si l'etat produit et l'emballage sont conformes.",
    "support.track-order.description": "Consultez l'avancement de traitement et de livraison de votre commande.",
    "support.track-order.content1": "Suivez votre commande avec le numero de commande et l'email de confirmation.",
    "support.track-order.content2": "Si le suivi n'est pas mis a jour dans les delais attendus, envoyez une demande de support pour escalade.",
    "support.help-center.description": "Parcourez les questions frequentes et les guides de configuration.",
    "support.help-center.content1": "Le centre d'aide inclut des guides d'installation, depannage de compte et articles d'assistance checkout.",
    "support.help-center.content2": "Utilisez les filtres par sujet pour trouver rapidement des reponses par famille de produits.",
    "support.store-location.description": "Trouvez les points de vente Growrix Auto et leurs horaires.",
    "support.store-location.content1": "Les magasins et comptoirs service sont listes avec leurs horaires locaux.",
    "support.store-location.content2": "Les details de reservation sont disponibles pour les magasins participants.",
    "support.customer-feedback.description": "Partagez vos retours produit et service avec notre equipe.",
    "support.customer-feedback.content1": "Les retours clients aident a prioriser les prochaines ameliorations du catalogue et des fonctionnalites.",
    "support.customer-feedback.content2": "Utilisez cette route pour soumettre des alertes qualite, suggestions ou commentaires apres achat.",
  },
  es: {
    "common.home": "Inicio",
    "common.shop": "Tienda",
    "common.account": "Cuenta",
    "common.login": "Iniciar sesion",
    "common.register": "Registro",
    "common.checkout": "Pago",
    "common.success": "Exito",
    "common.blog": "Blog",
    "common.search": "Buscar",
    "common.category": "Categoria",
    "common.contact": "Contacto",
    "common.about": "Nosotros",
    "common.dailyDeals": "Ofertas diarias",
    "common.readMore": "Leer mas",
    "common.loadMore": "Cargar mas",
    "common.submit": "Enviar",
    "common.remove": "Quitar",
    "common.goToShop": "Ir a la tienda",
    "common.continueShopping": "Seguir comprando",
    "common.viewAccount": "Ver cuenta",
    "common.clearCart": "Vaciar carrito",
    "common.proceedCheckout": "Continuar al pago",
    "common.placeOrder": "Realizar pedido",
    "common.by": "Por",
    "common.searchAction": "Buscar",

    "nav.hotline": "Linea directa",
    "nav.loginRegister": "Iniciar sesion / Registro",
    "nav.account": "Mi cuenta",
    "nav.logout": "Cerrar sesion",
    "nav.myCart": "Mi carrito",
    "nav.search": "Buscar",
    "nav.itemSingular": "articulo",
    "nav.itemPlural": "articulos",
    "nav.home": "INICIO",
    "nav.shop": "TIENDA",
    "nav.deals": "OFERTAS",
    "nav.under100": "BAJO 100",
    "nav.newArrivals": "NOVEDADES",
    "nav.blog": "BLOG",
    "nav.about": "NOSOTROS",
    "nav.contact": "CONTACTO",

    "footer.followUs": "SIGUENOS",
    "footer.newsletterTitle": "SUSCRIBETE AL BOLETIN",
    "footer.newsletterThanks": "Gracias, te has suscrito.",
    "footer.contactUs": "CONTACTO",
    "footer.storeLocation": "UBICACIONES",
    "footer.customerService": "SERVICIO AL CLIENTE",
    "footer.information": "INFORMACION",
    "footer.replicationNote": "Construido como escaparate Next.js listo para produccion.",

    "newsletter.title": "Suscripcion al boletin",
    "newsletter.description": "Suscribete para recibir novedades, ofertas especiales e informacion de descuentos.",
    "newsletter.subscribed": "Gracias, tu suscripcion esta activa.",
    "newsletter.doNotShow": "No mostrar este popup de nuevo",
    "newsletter.placeholder": "Tu correo electronico",
    "newsletter.cta": "SUSCRIBIRSE",

    "home.welcome": "Bienvenido a {siteName}",
    "home.heroTop": "LO MEJOR",
    "home.heroBottom": "TIENDA AUTOMOTRIZ",
    "home.heroDescription": "Una tienda automotriz completa con fuerte contraste, descubrimiento rapido y rutas de compra optimizadas.",
    "home.exploreNow": "EXPLORAR",
    "home.slide2Eyebrow": "Confianza lista para pista",
    "home.slide2Top": "PRECISION",
    "home.slide2Bottom": "FRENADO MEJORADO",
    "home.slide2Description": "Mejora el control con kits de freno de alto rendimiento y componentes reforzados para manejo diario y de fin de semana.",
    "home.slide2Cta": "VER KITS DE FRENO",
    "home.slide3Eyebrow": "Ahorra mas esta semana",
    "home.slide3Top": "OFERTAS",
    "home.slide3Bottom": "DIARIAS",
    "home.slide3Description": "Descubre descuentos rotativos en llantas, herramientas y repuestos antes de que termine la ventana de inventario.",
    "home.slide3Cta": "VER OFERTAS",
    "home.prevSlide": "Diapositiva anterior",
    "home.nextSlide": "Diapositiva siguiente",
    "home.selectVehicle": "Selecciona tu vehiculo",
    "home.vehicleSubtitle": "Mas de 120,000 piezas para auto y camion",
    "home.topSelection": "Seleccion destacada de la semana",
    "home.bestSellers": "Mas vendidos",
    "home.recentPosts": "Publicaciones recientes",
    "home.latestBlogs": "Ultimos blogs",
    "home.featureFreeShipping": "ENVIO GRATIS",
    "home.featureFreeShippingText": "En pedidos superiores a {amount}",
    "home.featureMoneyGuarantee": "GARANTIA DE DINERO",
    "home.featureMoneyGuaranteeText": "30 dias de garantia de reembolso",
    "home.featureSafeShopping": "COMPRA SEGURA",
    "home.featureSafeShoppingText": "Garantia de compra segura",
    "home.featureOnlineSupport": "SOPORTE EN LINEA",
    "home.featureOnlineSupportText": "Soporte 24/7 todos los dias",
    "home.newArrivals": "NOVEDADES",
    "home.bestSellersColumn": "MAS VENDIDOS",
    "home.saleOff": "OFERTAS",

    "shop.subtitle": "Descubre productos automotrices premium con rutas completas de busqueda y compra.",
    "shop.noProducts": "No hay productos disponibles en esta categoria por ahora.",

    "search.results": "RESULTADOS DE BUSQUEDA",
    "search.query": "Consulta",
    "search.make": "Marca",
    "search.model": "Modelo",
    "search.year": "Ano",
    "search.noResults": "No se encontraron productos. Prueba otra palabra clave o ajusta los filtros.",
    "search.placeholder": "Buscar productos",
    "search.selectMake": "Seleccionar marca",
    "search.selectModel": "Seleccionar modelo",
    "search.selectYear": "Seleccionar ano",

    "cart.title": "MI CARRITO",
    "cart.empty": "Tu carrito esta vacio. Explora la tienda para agregar productos.",
    "cart.subtotal": "Subtotal",

    "checkout.title": "PAGO",
    "checkout.orderSummary": "Resumen del pedido",
    "checkout.items": "Articulos",
    "checkout.empty": "Tu carrito esta vacio. Agrega productos antes de pagar.",
    "checkout.fullName": "Nombre completo",
    "checkout.email": "Correo electronico",
    "checkout.address": "Direccion",
    "checkout.city": "Ciudad",
    "checkout.postalCode": "Codigo postal",

    "checkout.successTitle": "PEDIDO CONFIRMADO",
    "checkout.successMessage": "Tu pedido se realizo correctamente. Puedes seguir comprando o revisar tu cuenta para ver el estado.",

    "product.sku": "SKU",
    "product.inStock": "En stock",
    "product.category": "Categoria",
    "product.addToCart": "Agregar al carrito",
    "product.added": "Agregado",
    "product.descriptionTitle": "Descripcion del producto",
    "product.featuresTitle": "Caracteristicas clave",
    "product.descriptionBody1": "{title} esta disenado para conductores que esperan rendimiento diario confiable y respuesta segura bajo carga.",
    "product.descriptionBody2": "Construido para el segmento {category}, este articulo equilibra durabilidad, precision de ajuste e instalacion limpia para proyectos automotrices modernos.",
    "product.featureCompatibility": "Compatibilidad alineada con configuraciones {category}",
    "product.featureInventory": "{stock} unidades disponibles para despacho rapido",
    "product.featureUseCase": "Recomendado para: {tags}",
    "product.featureWarranty": "Materiales probados para confiabilidad a largo plazo",

    "account.title": "MI CUENTA",
    "account.profileOverview": "Resumen del perfil",
    "account.profileDescription": "Manten tus preferencias actualizadas para idioma, moneda y pago predeterminados.",
    "account.currentPreferences": "Preferencias actuales",
    "account.language": "Idioma",
    "account.currency": "Moneda",
    "account.guestTitle": "Sesion de invitado",
    "account.guestDescription": "Inicia sesion o crea una cuenta para guardar tus preferencias.",
    "account.signInNow": "Iniciar sesion",
    "account.registerNow": "Crear cuenta",

    "auth.loginTitle": "INICIAR SESION",
    "auth.registerTitle": "REGISTRO",
    "auth.email": "Correo electronico",
    "auth.password": "Contrasena",
    "auth.signIn": "Ingresar",
    "auth.createAccount": "Crear cuenta",
    "auth.loginSuccess": "Inicio de sesion exitoso para esta demo.",
    "auth.registerSuccess": "Registro completado para esta demo.",
    "auth.noAccount": "No tienes una cuenta?",
    "auth.haveAccount": "Ya tienes una cuenta?",
    "auth.fullName": "Nombre completo",

    "contact.title": "CONTACTO",
    "contact.intro": "Nos encanta escucharte. Envia tus preguntas y responderemos en un plazo de 2 dias habiles.",
    "contact.name": "Nombre",
    "contact.phone": "Numero de telefono",
    "contact.message": "Deja un comentario",
    "contact.success": "Gracias, tu mensaje fue enviado.",
    "contact.submitting": "ENVIANDO...",
    "contact.submitFailed": "No se pudo enviar tu mensaje en este momento. Intentalo de nuevo.",

    "about.title": "SOBRE NOSOTROS",
    "about.intro1": "Growrix Auto es una tienda automotriz limpia enfocada en piezas premium, marcas confiables y una experiencia de compra rapida.",
    "about.intro2": "El diseno combina una jerarquia visual fuerte con descubrimiento practico de productos para sentirse como un comercio real.",
    "about.team": "Nuestro equipo",
    "about.locations": "Ubicaciones",

    "dailyDeals.title": "OFERTAS DIARIAS",
    "dailyDeals.days": "DIAS",
    "dailyDeals.hours": "HORAS",
    "dailyDeals.mins": "MINS",
    "dailyDeals.secs": "SEGS",

    "blog.related": "Entradas relacionadas",
    "support.titleFallback": "Soporte",
    "support.customer-service.description": "Recibe asistencia directa para preguntas de productos, pedidos y cuenta.",
    "support.customer-service.content1": "Nuestro equipo de atencion al cliente ayuda con actualizaciones de pedido, compatibilidad de productos y soporte de cuenta.",
    "support.customer-service.content2": "Usa esta pagina para solicitudes generales de servicio y ayuda por ruta.",
    "support.shipping-returns.description": "Revisa tiempos de envio y politicas de devolucion.",
    "support.shipping-returns.content1": "Las estimaciones de envio varian por region y tipo de producto. Las actualizaciones de seguimiento aparecen cuando el transportista escanea el paquete.",
    "support.shipping-returns.content2": "Las devoluciones se aceptan dentro de la ventana indicada cuando se cumple la condicion del producto y empaque.",
    "support.track-order.description": "Consulta el progreso de preparacion y entrega de tu pedido.",
    "support.track-order.content1": "Rastrea el estado de tu pedido con el numero de orden y correo de confirmacion.",
    "support.track-order.content2": "Si el seguimiento no se actualiza en el tiempo esperado, envia una solicitud de soporte para escalar el caso.",
    "support.help-center.description": "Explora preguntas frecuentes y guias de configuracion.",
    "support.help-center.content1": "El centro de ayuda incluye guias de instalacion, solucion de problemas de cuenta y articulos de soporte para checkout.",
    "support.help-center.content2": "Usa filtros por tema para encontrar respuestas por familia de productos rapidamente.",
    "support.store-location.description": "Encuentra ubicaciones y horarios de Growrix Auto.",
    "support.store-location.content1": "Las ubicaciones y mostradores de servicio se listan con horarios locales.",
    "support.store-location.content2": "Los detalles de reserva estan disponibles para ubicaciones participantes.",
    "support.customer-feedback.description": "Comparte comentarios sobre productos y servicio con nuestro equipo.",
    "support.customer-feedback.content1": "La retroalimentacion de clientes ayuda a priorizar mejoras de catalogo y funciones.",
    "support.customer-feedback.content2": "Usa esta ruta para enviar observaciones de calidad, sugerencias o comentarios despues de la compra.",
  },
};

type Replacements = Record<string, string | number>;

export function normalizeLanguage(value: string | null | undefined): LanguageCode {
  if (!value) return fallbackLanguage;
  const lower = value.toLowerCase();
  const fromCode = languageOptions.find((language) => language.code === lower);

  if (fromCode) {
    return fromCode.code;
  }

  const upper = value.toUpperCase();
  const fromLabel = languageOptions.find((language) => language.label === upper);
  return fromLabel ? fromLabel.code : fallbackLanguage;
}

export function normalizeCurrency(value: string | null | undefined): CurrencyCode {
  if (!value) return fallbackCurrency;
  const upper = value.toUpperCase();
  return currencyOptions.find((currency) => currency === upper) ?? fallbackCurrency;
}

export function getLanguageLabel(language: LanguageCode) {
  return languageOptions.find((item) => item.code === language)?.label ?? languageOptions[0].label;
}

export function getLanguageLocale(language: LanguageCode) {
  return languageOptions.find((item) => item.code === language)?.locale ?? languageOptions[0].locale;
}

export function convertUsdPrice(price: number, currency: CurrencyCode) {
  return price * currencyRatesFromUsd[currency];
}

export function formatPriceByPreference(price: number, currency: CurrencyCode, language: LanguageCode) {
  const converted = convertUsdPrice(price, currency);
  const locale = getLanguageLocale(language);

  return new Intl.NumberFormat(locale, {
    style: "currency",
    currency,
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(converted);
}

export function translate(language: LanguageCode, key: string, replacements: Replacements = {}) {
  const dictionary = messages[language] ?? messages.en;
  const fallback = messages.en;
  const template = dictionary[key] ?? fallback[key] ?? key;

  return template.replace(/\{(\w+)\}/g, (match, token: string) => {
    const value = replacements[token];
    return value === undefined ? match : String(value);
  });
}

export function translateByBreadcrumbLabel(language: LanguageCode, label: string) {
  const normalized = label.trim().toLowerCase();
  const keyMap: Record<string, string> = {
    home: "common.home",
    shop: "common.shop",
    account: "common.account",
    login: "common.login",
    register: "common.register",
    checkout: "common.checkout",
    success: "common.success",
    blog: "common.blog",
    search: "common.search",
    "my cart": "cart.title",
    "contact us": "common.contact",
    "about us": "common.about",
    "daily deals": "common.dailyDeals",
    category: "common.category",
  };

  const translationKey = keyMap[normalized];
  return translationKey ? translate(language, translationKey) : label;
}